# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rc/main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from moduls.vievs_moduls.PhotoViewer import PhotoViewer

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 814)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background: #3E454B;\n"
"}\n"
"\n"
"QLabel{\n"
"color: #fff;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
" background: #2EE59D;\n"
"  box-shadow: 0 15px 20px rgba(46,229,157,.4);\n"
"  color: white;\n"
"  transform: translateY(-7px); \n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"\n"
"  text-decoration: none;\n"
"  outline: none;\n"
"  display: inline-block;\n"
"  width: 140px;\n"
"  height: 45px;\n"
"  line-height: 45px;\n"
"  border-radius: 45px;\n"
"  margin: 10px 20px;\n"
"  font-family: \'Montserrat\', sans-serif;\n"
"  font-size: 11px;\n"
"  text-transform: uppercase;\n"
"  text-align: center;\n"
"  letter-spacing: 3px;\n"
"  font-weight: 600;\n"
"  color: #524f4e;\n"
"  background: white;\n"
"  box-shadow: 0 8px 15px rgba(0,0,0,.1);\n"
"  transition: .3s;\n"
"border-radius: 20px;\n"
" }\n"
"\n"
"QPushButton:pressed {\n"
"    color: #111;\n"
"    border: 1px solid #3873d9;\n"
"    background: #fff;\n"
" }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(10)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid #C2C7CB;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 5px; /* move to the right by 5px */\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 2px solid #C4C4C3;\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 20ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    \n"
"    background: #2EE59D;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.formLayout)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("Montserrat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        self.gridLayout_2.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("Montserrat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 0, 1, 1)
        
        
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 3, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 3, 1, 1, 1)
        self.graphicsView = PhotoViewer(self.tab_2)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_3.addWidget(self.graphicsView, 1, 0, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 3)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_3.addWidget(self.pushButton_12, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setMaximumSize(QtCore.QSize(820, 111))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.horizontalLayout_2.addLayout(self.formLayout_4)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 3)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Montserrat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_4.addWidget(self.pushButton_11, 2, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Montserrat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_4.addWidget(self.pushButton_10, 2, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Montserrat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_4.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 500))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_photo_3 = QtWidgets.QLabel(self.groupBox)
        self.label_photo_3.setObjectName("label_photo_3")
        self.gridLayout_5.addWidget(self.label_photo_3, 0, 2, 1, 1)
        self.label_photo_7 = QtWidgets.QLabel(self.groupBox)
        self.label_photo_7.setObjectName("label_photo_7")
        self.gridLayout_5.addWidget(self.label_photo_7, 1, 1, 1, 1)
        self.label_photo_8 = QtWidgets.QLabel(self.groupBox)
        self.label_photo_8.setObjectName("label_photo_8")
        self.gridLayout_5.addWidget(self.label_photo_8, 1, 2, 1, 1)
        self.label_photo_4 = QtWidgets.QLabel(self.groupBox)
        self.label_photo_4.setObjectName("label_photo_4")
        self.gridLayout_5.addWidget(self.label_photo_4, 0, 3, 1, 1)
        self.label_photo_9 = QtWidgets.QLabel(self.groupBox)
        self.label_photo_9.setObjectName("label_photo_9")
        self.gridLayout_5.addWidget(self.label_photo_9, 1, 3, 1, 1)
        self.label_photo_10 = QtWidgets.QLabel(self.groupBox)
        self.label_photo_10.setObjectName("label_photo_10")
        self.gridLayout_5.addWidget(self.label_photo_10, 1, 4, 1, 1)
        self.label_photo_5 = QtWidgets.QLabel(self.groupBox)
        self.label_photo_5.setObjectName("label_photo_5")
        self.gridLayout_5.addWidget(self.label_photo_5, 0, 4, 1, 1)
        self.label_photo_6 = QtWidgets.QLabel(self.groupBox)
        self.label_photo_6.setObjectName("label_photo_6")
        self.gridLayout_5.addWidget(self.label_photo_6, 1, 0, 1, 1)
        self.label_photo_2 = QtWidgets.QLabel(self.groupBox)
        self.label_photo_2.setObjectName("label_photo_2")
        self.gridLayout_5.addWidget(self.label_photo_2, 0, 1, 1, 1)
        self.label_photo_1 = QtWidgets.QLabel(self.groupBox)
        self.label_photo_1.setObjectName("label_photo_1")
        self.gridLayout_5.addWidget(self.label_photo_1, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.graphicsView)
        MainWindow.setTabOrder(self.graphicsView, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.lineEdit_7)
        """
        #self.tabWidget.setTabEnabled(0,False); # отключаем принудительные переходы
        self.tabWidget.setTabEnabled(1,False);# отключаем принудительные переходы
        self.tabWidget.setTabEnabled(2,False);# отключаем принудительные переходы
        """
        self.tab_setTabEnabled(0)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Фотографирования"))
        self.label.setText(_translate("MainWindow", "Фамилия:"))
        self.label_2.setText(_translate("MainWindow", "Имя:"))
        self.label_3.setText(_translate("MainWindow", "Отчество:"))
        self.pushButton.setText(_translate("MainWindow", "Добавить пользователя"))
        self.pushButton_2.setText(_translate("MainWindow", "Приступить к фотографированию"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Поиск"))
        self.pushButton_4.setText(_translate("MainWindow", "Далее"))
        self.pushButton_3.setText(_translate("MainWindow", "Сфотографировать"))
        self.label_5.setText(_translate("MainWindow", "Фотографирования обычной камерой"))
        self.pushButton_12.setText(_translate("MainWindow", "отмена"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Фото RGB"))
        self.label_7.setText(_translate("MainWindow", "Фамилия:"))
        self.label_8.setText(_translate("MainWindow", "Имя:"))
        self.label_9.setText(_translate("MainWindow", "Отчество:"))
        self.pushButton_11.setText(_translate("MainWindow", "сохранить и обучить"))
        self.pushButton_10.setText(_translate("MainWindow", "Отмена"))
        self.pushButton_9.setText(_translate("MainWindow", "Сохранить"))
        self.groupBox.setTitle(_translate("MainWindow", "Фото"))
        self.label_photo_3.setText(_translate("MainWindow", "photo"))
        self.label_photo_7.setText(_translate("MainWindow", "photo"))
        self.label_photo_8.setText(_translate("MainWindow", "photo"))
        self.label_photo_4.setText(_translate("MainWindow", "photo"))
        self.label_photo_9.setText(_translate("MainWindow", "photo"))
        self.label_photo_10.setText(_translate("MainWindow", "photo"))
        self.label_photo_5.setText(_translate("MainWindow", "photo"))
        self.label_photo_6.setText(_translate("MainWindow", "photo"))
        self.label_photo_2.setText(_translate("MainWindow", "photo"))
        self.label_photo_1.setText(_translate("MainWindow", "photo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Сохранения данных"))
        self.action.setText(_translate("MainWindow", "Настройки"))
        self.action_2.setText(_translate("MainWindow", "Выход"))
    
    def tab_setTabEnabled(self, i):
        self.tabWidget.setTabEnabled(0,False);
        self.tabWidget.setTabEnabled(1,False);
        self.tabWidget.setTabEnabled(2,False);
        try:
            self.tabWidget.setTabEnabled(i,True);
        except:
            self.showMessage("tab_setTabEnabled err")